# Generated by Django 3.1 on 2020-08-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confBySms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
