# Generated by Django 3.1 on 2020-08-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confBySms', '0002_auto_20200816_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
